# Math library

In [1]:
import math

In [2]:
math.ceil(1.56)

2

In [8]:
math.floor(1.56)

1

In [4]:
math.factorial(5)

120

In [7]:
math.copysign(15.0,-7)

-15.0

In [9]:
math.gcd(5,10)

5

In [19]:
math.exp(3)
#e= 2.718281...

20.085536923187668

In [26]:
math.log(6)
#num,base
#by default base e

1.791759469228055

In [28]:
math.sqrt(10)

3.1622776601683795

In [31]:
math.sin(90)
#x is in radians

0.8939966636005579

In [51]:
math.sin(math.radians(int(input('Enter input in degrees'))))


Enter input in degrees0


0.0

In [52]:
math.radians(90.0)

1.5707963267948966

In [53]:
math.pi

3.141592653589793

In [54]:
math.e

2.718281828459045

# Numpy

In [55]:
import numpy as np

In [56]:
arr = np.array([1, 2, 3])

In [57]:
print(arr)

[1 2 3]


In [63]:
arr = np.array([[1, 2, 3],
                [4, 5,6]])

In [64]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [66]:
arr = np.array((1, 3, 2))
print('array created from a tuple is',arr)

array created from a tuple is [1 3 2]


In [67]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [71]:
arr[3]

array([ 3., -7.,  4.,  2.])

In [72]:
arr[3][3]

2.0

In [75]:
arr[::2]

array([[-1. ,  2. ,  0. ,  4. ],
       [ 2.6,  0. ,  7. ,  8. ]])

In [76]:
arr.shape

(4, 4)

In [93]:
arr = np.array([[-1, 2, 0, 4],
                [4, -4, 6, 0],
                [2, 0, 7, 8],
                [3, -7, 4, 2]])
arr.T #Transpose

array([[-1,  4,  2,  3],
       [ 2, -4,  0, -7],
       [ 0,  6,  7,  4],
       [ 4,  0,  8,  2]])

In [94]:
arr.size

16

In [96]:
arr.itemsize #array elements are integers

4

In [97]:
arr.nbytes

64

In [116]:
a=np.array([[1,2],[3,9]])

In [117]:
a

array([[1, 2],
       [3, 9]])